var conditions = {
	tangled: {
		name: "Tangled",
		skin: "condition_bad",
		explanation: "Sets maximum speed to 24.",
		ui: false,
		debuff: true,
		set_speed: 24,
		duration: 12000,
	},
	sugarrush: {
		skin: "candycanesword",
		name: "Sugar Rush",
		frequency: 240,
		duration: 10 * 1000,
		mp_cost: -200,
		buff: true,
		ui: true,
		explanation: "Greatly increases attack speed and reduces mana cost of attacks.",
	},
	power: {
		skin: "powerglove",
		name: "Power",
		frequency: 360,
		duration: 4 * 1000,
		mp_cost: -200,
		buff: true,
		ui: true,
		explanation: "Increases attack speed and reduces mana cost.",
	},
	weakness: {
		skin: "condition_bad",
		name: "Weakness",
		debuff: true,
		ui: true,
		speed: -30,
		dex: -10,
		str: -10,
		duration: 20000,
		explanation: "Reduces speed, dexterity, and strength.",
	},
	xpower: {
		skin: "goldenpowerglove",
		name: "Power",
		frequency: 480,
		duration: 6 * 1000,
		mp_cost: -300,
		buff: true,
		ui: true,
		explanation: "Greatly increases attack speed and lowers mana cost.",
	},
	stack: {
		skin: "skill_stack",
		name: "Pure Damage",
		explanation: "Bonus damage for each rogue attack.",
		debuff: true,
	},
	woven: {
		skin: "spidersilk",
		name: "Woven",
		explanation: "Reduces speed by 3 per stack. Stacks up to 20 on monsters, capped at 5 for players.",
		ui: true,
		debuff: true,
		speed: -10,
		duration: 1000,
	},
	energized: {
		skin: "skill_energize",
		name: "Energized",
		buff: true,
		frequency: 80,
		duration: 800,
		buff: true,
		ui: true,
		explanation: "Gives a brief burst of attack speed.",
	},
	mcourage: {
		skin: "skill_mcourage",
		name: "Merchant's Courage",
		speed: 25,
		evasion: 40,
		courage: 5,
		mcourage: 5,
		pcourage: 5,
		duration: 10000,
		ui: true,
		buff: true,
		explanation: "Increases speed, evasion, and all types of courage.",
	},
	mfrenzy: {
		skin: "skill_mfrenzy",
		name: "Merchant's Frenzy",
		frequency: 800,
		duration: 5000,
		mp_cost: -20,
		output: 40,
		ui: true,
		buff: true,
		explanation: "Greatly boosts attack speed and output while lowering mana cost.",
	},
	mshield: {
		skin: "skill_mshield",
		name: "Mana Shield",
		ui: true,
		buff: true,
		explanation: "Mana absorbs damage before health.",
	},
	phasedout: {
		skin: "skill_phaseout",
		name: "Phased Out",
		frequency: -40,
		speed: -16,
		evasion: 64,
		duration: 5000,
		ui: true,
		buff: true,
		explanation: "Decreases attack and movement speed but greatly increases evasion.",
	},
	hardshell: {
		skin: "skill_hardshell",
		name: "Hard Shell",
		armor: 800,
		set_speed: 10,
		duration: 8000,
		buff: true,
		explanation: "Greatly increases armor but limits maximum speed to 10.",
	},
	reflection: {
		skin: "buff_reflection",
		name: "Reflective Shield",
		reflection: 20,
		cap_reflection: 50,
		duration: 5000,
		ui: true,
		buff: true,
		explanation: "Increases your chance to reflect attacks.",
	},
	eburn: {
		skin: "essenceoffire",
		name: "Burn",
		intensity: "burnd",
		interval: 200,
		damage: 50,
		duration: 12 * 1000,
		speed: 5,
		ui: true,
		debuff: true,
		explanation: "Burns the target with fire essence, dealing damage over time.",
	},
	newcomersblessing: {
		skin: "newcomersblessing",
		name: "Newcomers' Blessing",
		duration: 30 * 60 * 1000,
		luck: 10,
		gold: 10,
		xp: 10,
		aura: true,
		ui: true,
		persistent: true,
		explanation: "Increases luck, gold gain, and experience earned.",
	},
	eheal: {
		skin: "essenceoflife",
		name: "Rejuvenate",
		interval: 320,
		heal: 200,
		duration: 4 * 1000,
		ui: true,
		buff: true,
		explanation: "Heals the target over time using life essence.",
	},
	rspeed: {
		skin: "buff_speed",
		name: "Rogue Swiftness",
		speed: 7,
		frequency: 8,
		duration: 45 * 60 * 1000,
		buff: true,
		ui: true,
		explanation: "Increases movement speed and attack speed.",
	},
	massproduction: {
		skin: "skill_massproduction",
		name: "Mass Production",
		explanation: "Reduces the time of your next upgrade or compound by 50%.",
		duration: 10 * 1000,
		buff: true,
		ui: true,
	},
	massproductionpp: {
		skin: "skill_massproductionpp",
		name: "Mass Production++",
		explanation: "Reduces the time of your next upgrade or compound by 90%.",
		duration: 10 * 1000,
		buff: true,
		ui: true,
	},
	massexchange: {
		skin: "skill_massexchange",
		name: "Mass exchange",
		explanation: "Reduces the time of your next exchange by 50%.",
		duration: 10 * 1000,
		buff: true,
		ui: true,
	},
	massexchangepp: {
		skin: "skill_massexchangepp",
		name: "Mass exchange++",
		explanation: "Reduces the time of your next exchange by 90%.",
		duration: 10 * 1000,
		buff: true,
		ui: true,
	},
	darkblessing: {
		skin: "skill_dbuff",
		name: "Dark Blessing",
		output: 25,
		duration: 8 * 1000,
		buff: true,
		ui: true,
		explanation: "Increases damage output.",
	},
	warcry: {
		skin: "skill_warcry",
		name: "War Cry",
		frequency: 10,
		speed: 20,
		armor: 160,
		resistance: 160,
		duration: 8 * 1000,
		buff: true,
		ui: true,
		explanation: "Boosts attack speed, movement speed, armor, and resistance.",
	},
	purifier: {
		skin: "skill_purify",
		name: "Purifier",
		frequency: 20,
		output: 20,
		str: 30,
		duration: 8 * 1000,
		buff: true,
		ui: true,
		explanation: "Boosts attack speed, damage output, and strength.",
	},
	mluck: {
		skin: "buff_luck",
		name: "Good Luck",
		luck: 12,
		duration: 60 * 60 * 1000,
		buff: true,
		ui: true,
		persistent: true,
		explanation: "Lucked!",
	},
	withdrawal: {
		skin: "withdrawal",
		name: "Withdrawal",
		speed: -20,
		frequency: -30,
		dex: -20,
		str: -5,
		mp: -300,
		duration: 180 * 60 * 1000,
		ui: true,
		debuff: true,
		persistent: true,
		explanation: "Reduced stats.",
	},
	penalty_cd: {
		skin: "condition_bad",
		name: "Penalty Cooldown",
		explanation: "The remaining duration of this condition is added any skill you use. Teleporting adds 3s, magiporting adds around 800ms, some item operations add 100-200ms.",
		debuff: true,
	},
	xshotted: {
		skin: "xshotted",
		name: "X-Shot",
		explanation: "Good luck trying to find a tavern to play in.",
		duration: 12 * 60 * 60 * 1000,
		debuff: true,
		ui: true,
		persistent: true,
	},
	patronsgrace: {
		skin: "patronsgrace",
		name: "Patron's Grace",
		explanation: "This server has been graced by a patron's support!",
		luck: 5,
		gold: 20,
		xp: 25,
		speed: 1,
		duration: 2 * 60 * 1000,
		buff: true,
		ui: true,
	},
	notverified: {
		skin: "notverified",
		name: "Not Verified",
		explanation: "Reduced luck and gold until the associated email address is verified.",
		luck: -25,
		gold: -25,
		debuff: true,
		technical: true,
		ui: true,
		persistent: true,
	},
	authfail: {
		skin: "notverified",
		name: "Authorization Failure",
		explanation:
			"Your account has failed an internal authorization routine. This might've happened if you haven't logged on from Steam or Mac App Store since this new system was implemented. Just visit the bank with a game client and the issue should resolve. If it persists unexpectedly email hello@adventure.land.",
		luck: -85,
		gold: -85,
		xp: -20,
		debuff: true,
		technical: true,
		ui: true,
		persistent: true,
	},
	hopsickness: {
		skin: "condition_bad",
		name: "Hop Sickness",
		explanation: "You are not in your home server! Go see Bean in Mainland square for a change.",
		luck: -80,
		gold: -80,
		xp: -80,
		output: -20,
		ui: true,
		debuff: true,
		persistent: true,
		duration: 1000 * 60 * 12,
		special: "snakeoil",
	},
	fullguard: {
		skin: "fullguard",
		name: "Full Guard",
		ui: true,
		resistance: 10000,
		armor: 10000,
		buff: true,
		persistent: true,
		explanation: "Providing maximum resistance and armor.",
	},
	fullguardx: {
		skin: "fullguard",
		name: "Full Guard",
		ui: true,
		avoidance: 99,
		buff: true,
		persistent: true,
		explanation: "Increasing avoidance to near perfect.",
	},
	stunned: {
		name: "Stunned",
		skin: "condition_bad",
		ui: true,
		blocked: true,
		debuff: true,
		defense: "phresistance",
		duration: 3200,
		explanation: "Cannot move, attack, heal, or use skills.",
	},
	deepfreezed: {
		name: "Deepfreezed",
		skin: "condition_bad",
		duration: 12000,
		ui: true,
		blocked: true,
		debuff: true,
		defense: "fzresistance",
		explanation: "Cannot move, attack, heal, or use skills.",
	},
	invincible: {
		name: "Invincible",
		skin: "condition_positive",
		explanation: "When you spawn in a PVP area. This prevents you from receiving damage or marked as engaged in PVP. If you get attacked, disconnect before this runs out - or fight!",
		duration: 6000,
		persistent: true,
	},
	frozen: {
		name: "Frozen",
		skin: "frostbow",
		ui: true,
		debuff: true,
		duration: 5000,
		frequencym: 0.3,
		speed: -40,
		defense: "fzresistance",
		explanation: "Reduces speed by 40 and frequency by 70%.",
	},
	burned: {
		name: "Burned",
		skin: "fireblade",
		interval: 210,
		ui: true,
		debuff: true,
		defense: "firesistance",
		explanation: "Burns the target for damage equal to its intensity per second.",
	},
	shocked: {
		name: "Shocked",
		skin: "essenceofthunder",
		explanation: "Imminent magical damage.",
		duration: 1600,
		ui: true,
		debuff: true,
	},
	fingered: {
		name: "Deep Meditation",
		skin: "condition_neutral",
		resistance: 1600,
		evasion: 96,
		blocked: true,
		debuff: true,
		explanation: "Stunned for the duration.",
	},
	stoned: {
		name: "Stoned",
		skin: "condition_neutral",
		duration: 4000,
		blocked: true,
		debuff: true,
		// "defense":"bmresistance",
		explanation: "Cannot move, attack, heal, or use skills.",
	},
	easterluck: {
		skin: "easterluck",
		name: "Easter Luck",
		luck: 100,
		duration: 24 * 60 * 60 * 1000,
		buff: true,
		ui: true,
		persistent: true,
		explanation: "Luck is greatly increased.",
	},
	sanguine: {
		skin: "sanguine",
		name: "Vampiric Aura",
		attr0: "lifesteal",
		buff: true,
		ui: true,
		aura: true,
		duration: 30 * 1000,
		explanation: "Bite back with every hit.",
	},
	mlifesteal: {
		skin: "lifestealscroll",
		name: "Lifesteal",
		lifesteal: 2.5,
		duration: 60 * 60 * 1000,
		buff: true,
		ui: true,
		explanation: "Fresh from vampire slaying.",
	},
	holidayspirit: {
		skin: "holidayspirit",
		//"name":"Xmas Spirit",
		name: "Holiday Spirit",
		luck: 20,
		gold: 20,
		xp: 20,
		duration: 24 * 60 * 60 * 1000,
		buff: true,
		ui: true,
		persistent: true,
		explanation: "Feel the festive vibes luck, gold, and XP boosted!",
	},
	halloween0: {
		skin: "halloween0",
		name: "Halloween Spirit",
		luck: 5,
		gold: 5,
		xp: 100,
		duration: 48 * 60 * 60 * 1000,
		buff: true,
		ui: true,
		persistent: true,
		explanation: "A full-on Halloween blast with tons of XP to haunt your day.",
	},
	halloween1: {
		skin: "halloween1",
		name: "Halloween Spirit",
		luck: 5,
		gold: 5,
		xp: 50,
		output: 2,
		duration: 24 * 60 * 60 * 1000,
		buff: true,
		ui: true,
		persistent: true,
		explanation: "A nice spooky boost to luck and XP.",
	},
	halloween2: {
		skin: "halloween2",
		name: "Halloween Spirit",
		output: 3,
		luck: 5,
		gold: 5,
		xp: 10,
		duration: 8 * 60 * 60 * 1000,
		buff: true,
		ui: true,
		persistent: true,
		explanation: "A quick touch of Halloween magic to boost luck and gold.",
	},
	// "xmas":{
	// 	"skin":"xmas",
	// 	//"name":"Xmas Spirit",
	// 	"name":"Blessing of 2018",
	// 	"luck":200,
	// 	"gold":200,
	// 	"xp":200,
	// 	"duration":24*60*60*1000,
	// 	"buff":true,
	// 	"ui":true,
	// },
	// "xmas2":{
	// 	"skin":"xmas",
	// 	//"name":"Xmas Spirit",
	// 	"name":"Blessing of 2019",
	// 	"luck":50,
	// 	"gold":50,
	// 	"xp":50,
	// 	"evasion":10,
	// 	//"ability":"secondchance",
	// 	//"attr0":20,
	// 	"duration":48*60*60*1000,
	// 	"buff":true,
	// 	"ui":true,
	// 	"note":"Technically our third new year, second year of our tree and the buff :)"
	// },
	slowness: {
		skin: "slowness",
		name: "Slowness",
		skin: "condition_neutral",
		explanation: "Things like spiderwebs cause you to slow down.",
		speed: -40,
		ui: true,
		debuff: true,
	},
	poisoned: {
		name: "Poison",
		skin: "poison",
		duration: 5000,
		frequencym: 0.9,
		potionsm: 0.5,
		healm: 0.25,
		debuff: true,
		defense: "pnresistance",
		explanation: "Reduces attack speed by 10%. All potions are 50% less effective. Healing effects are 75% less effective.",
	},
	cursed: {
		name: "Cursed",
		skin: "condition_bad",
		output: -20,
		incdmgamp: 20,
		speed: -20,
		duration: 5000,
		debuff: true,
		// "defense":"bmresistance",
		explanation: "Reduces damage output and speed by 20%. Increases damage taken by 20%.",
	},
	dampened: {
		name: "Dampened",
		skin: "dampened",
		explanation: "Can't blink or teleport.",
		duration: 300,
		debuff: true,
	},
	poisonous: {
		skin: "skill_pcoat",
		name: "Poisonous",
		ui: true,
		buff: true,
		duration: 5000,
		explanation: "Your attacks apply Poison.",
	},
	invis: {
		skin: "skill_invis",
		name: "Invisible",
		explanation: "Hidden from everyone else until you attack.",
		buff: true,
	},
	licenced: {
		skin: "licence",
		name: "Licenced to Kill",
		explanation: "A special, temporary immunity.",
		ui: true,
		buff: true,
	},
	charmed: {
		skin: "charmer",
		name: "Charmed",
		explanation: "Mellow like a warm kitty.",
		ui: true,
		duration: 30000,
		debuff: true,
	},
	monsterhunt: {
		skin: "quest_monsterhunt",
		name: "On The Hunt",
		ui: true,
		duration: 1800000,
		persistent: true,
		explanation: "Tracking a target.",
	},
	// TODO: should be named quest, and used as a general purpose, the quest should also be able to override the skin
	quest_beekeeper: {
		skin: "quest_monsterhunt",
		name: "Bee On The Hunt",
		explanation: "Completing a Beekeeper kill quest.",
		ui: true,
		duration: 1800000,
		persistent: true,
	},
	marked: {
		skin: "skill_huntersmark",
		name: "Marked",
		explanation: "Marked by a ranger for death. Receive 10% more damage and can't stealth.",
		ui: true,
		incdmgamp: 10,
		duration: 10000,
		debuff: true,
	},
	charging: {
		name: "Charging",
		skin: "condition_positive",
		speed: 30,
		duration: 3200,
		explanation: "A short burst of speed.",
	},
	dash: {
		name: "Dashing",
		skin: "condition_positive",
		set_speed: 500,
		persistent: true,
	},
	blink: {
		name: "Blinking",
		skin: "condition_positive",
		explanation: "Blink in progress",
	},
	block: {
		name: "PVP Block",
		skin: "condition_neutral",
		explanation: "After engaging in PVP, blocked from safely leaving!",
		debuff: true,
		persistent: true,
	},
	town: {
		name: "Town",
		skin: "condition_positive",
		explanation: "Town in progress.",
		channel: true,
		can_move: true,
		duration: 3000,
	},
	fishing: {
		name: "Fishing",
		skin: "skill_fishing",
		explanation: "Fishing in progress.",
		channel: true,
		duration_min: 5000,
		duration: 15000,
	},
	mining: {
		name: "Mining",
		skin: "skill_mining",
		explanation: "Mining in progress.",
		channel: true,
		duration_min: 5000,
		duration: 15000,
	},
	pickpocket: {
		name: "Pickpocket",
		skin: "skill_pickpocket",
		explanation: "Pickpocket in progress.",
		channel: true,
		duration_min: 200,
		duration: 2200,
	},
	sleeping: {
		debuff: true,
		name: "Sleeping",
		duration_min: 3000,
		duration: 8000,
	},
	beekeeper_aura: {
		skin: "placeholder",
		gold: 1,
		// xp: 1,
		name: "Beekeeper Aura",
		attr0: "gold", // We can only give one attribute as an aura currently
		// attr1: "xp",
		buff: true,
		ui: true,
		aura: true,
		duration: 30 * 1000,
	},
	bee_pheromones_attack: {
		skin: "placeholder",
		name: "Pheromone: Attack",
		interval: 5000, // Handle targeting every 5 seconds
		range: 100, // The minimum range for the bee to attack target
		duration: 10 * 1000,
		ui: true,
		buff: true,
		// Idle minions with this condition aggro players in range
		idle_aggro: true,
		explanation: "A spawned minion without a target will aggro you if you get too close",
	},
	bee_pheromones_heal: {
		skin: "placeholder",
		name: "Pheromone: Heal",
		interval: 3000, // Heal every 3 seconds
		heal: 350,
		range: 100, // The minimum range for the bee to heal the queen
		duration: 10 * 1000,
		ui: true,
		buff: true,
		// Heal monsters of this type (queen); others can reuse with a different type
		heal_type: "bee_queen",
		explanation: "Will aid & tend to the queen, healing the queen.",
	},
};

// The tarot card condition generation block below was disabled in the original Python (if 0:)
// It is preserved here as a comment for reference.
//
// if(false){
// 	for(var name in games["tarot"]["cards"]){
// 		conditions["tarot_"+name]={"skin":"tarot","name":"Tarot Card","type":"tarot","ui":true};
// 		var num_vals=[["2",2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9],["10",10],["ace",20],["king",15],["knight",17],["page",12],["queen",14]];
// 		for(var i=0;i<num_vals.length;i++){
// 			var num=num_vals[i][0], val=num_vals[i][1];
// 			var color="";
// 			if(name.indexOf(num)!==-1 && name.indexOf("swords")!==-1){
// 				conditions["tarot_"+name]["str"]=val; color="swords";
// 			}
// 			if(name.indexOf(num)!==-1 && name.indexOf("wands")!==-1){
// 				conditions["tarot_"+name]["int"]=val; color="wands";
// 			}
// 			if(name.indexOf(num)!==-1 && name.indexOf("cups")!==-1){
// 				conditions["tarot_"+name]["dex"]=val; color="cups";
// 			}
// 			if(name.indexOf(num)!==-1 && name.indexOf("pentacles")!==-1){
// 				conditions["tarot_"+name]["vit"]=-val; color="pentacles";
// 			}
// 			if(color){
// 				conditions["tarot_"+name]["minor"]=num+"_"+color;
// 				conditions["tarot_"+name]["card"]=color.charAt(0).toUpperCase()+color.slice(1)+" of "+num.charAt(0).toUpperCase()+num.slice(1);
// 			}
// 		}
// 		if(name==="fool"){
// 			conditions["tarot_"+name]["miss"]=50;
// 		}
// 		if(name==="chariot"){
// 			conditions["tarot_"+name]["speed"]=16;
// 		}
// 		if(name==="death"){
// 			conditions["tarot_"+name]["vit"]=-30;
// 			conditions["tarot_"+name]["frequency"]=-30;
// 			conditions["tarot_"+name]["speed"]=-20;
// 		}
// 		if(name==="devil"){
// 			conditions["tarot_"+name]["xp"]=-99;
// 			conditions["tarot_"+name]["luck"]=-99;
// 			conditions["tarot_"+name]["vit"]=10;
// 			conditions["tarot_"+name]["str"]=10;
// 		}
// 		if(!conditions["tarot_"+name]["minor"]){
// 			conditions["tarot_"+name]["card"]=name.charAt(0).toUpperCase()+name.slice(1);
// 			conditions["tarot_"+name]["major"]=name;
// 		}
// 	}
// }
