var tokens={
	"funtoken":{
		"confetti":0.01,
		"smoke":0.05,
		"partyhat":2,
		"mshield":10,
		"rabbitsfoot":120,
		"xshield":200,
		"exoarm":999,
	},
	"pvptoken":{
		"hammer":120,
		"harbringer":25,
		"spear":1,
		"t2bow":1,
		"weaponbox":1,
		"armorbox":1,
	},
	"monstertoken":{
		"funtoken":20,
		"tracker":4,
		"armorbox":5,
		"troll":14,
		"networkcard":2000,
		"mwgloves":8, "mwarmor":12, "mwpants":11, "mwhelmet":7, "mwboots":15,
		"mmgloves":8, "mmarmor":12, "mmpants":11, "mmhat":7, "mmshoes":15,
		"mpgloves":8, "mparmor":12, "mppants":11, "mphat":7, "mpshoes":15,
		"mrngloves":8, "mrnarmor":12, "mrnpants":11, "mrnhat":7, "mrnboots":15,
		"mrgloves":8, "mrarmor":12, "mrpants":11, "mrhood":7, "mrboots":15,
		"mcgloves":8, "mcarmor":12, "mcpants":11, "mchat":7, "mcboots":15,
		"fieldgen0":100,
	},
	"friendtoken":{
		"cxjar-xgravestone2":4,
	},
	"beetoken":{
		// Cheap pots (<1 => quantity per token). Mats are exchange sinks only, not sold here.
		"honeypot":0.2,
		"honeypot1":0.5,
		"honeyelixir":5,
		// Same loot table as queen beeset open — priced above a queen-quest paycheck
		"beebox":15,
		// Guaranteed set pieces (expensive-first; ~2x+ box)
		"honeyhelmet":35,
		"honeychest":35,
		"honeypants":35,
		"honeyboots":35,
		"honeygloves":35,
		"honeysource":35,
		"honeyquiver":35,
		"honeyshield":35,
		"honeyamulet":40,
		"honeyring":40,
		"honeyearring":40,
		"honeybelt":40,
		"honeycape":40,
		"honeyorb":40,
		// Long endgame vanity chase
		"cxjar-beekeeper":2000,
	},
};
