/** AdventureLand CODE API ambient types (IDE only). Generated from docs/directory.js */
declare const character: Character;
declare const game: any;
declare const entities: { [id: string]: Entity };
declare const party: string[];
declare const safeties: boolean;

interface Entity {
	id?: string;
	name?: string;
	x: number;
	y: number;
	hp: number;
	max_hp: number;
	mp: number;
	max_mp: number;
	type?: string;
	mtype?: string;
	ctype?: string;
	map?: string;
	level?: number;
	range?: number;
	speed?: number;
	target?: string;
	npc?: boolean;
	player?: boolean;
	monster?: boolean;
	[key: string]: any;
}

interface Character extends Entity {
	name: string;
	cType?: string;
	gold: number;
	xp: number;
	items: any[];
	slots: { [slot: string]: any };
	moving?: boolean;
	range: number;
}

declare function start_character(...args: any[]): any;
declare function stop_character(...args: any[]): any;
declare function command_character(...args: any[]): any;
declare function get_active_characters(...args: any[]): any;
declare function change_server(...args: any[]): any;
declare function in_pvp(...args: any[]): any;
declare function is_npc(...args: any[]): any;
declare function is_monster(...args: any[]): any;
declare function is_character(...args: any[]): any;
declare function interact(...args: any[]): any;
declare function use_nearest_door(...args: any[]): any;
declare function enter(...args: any[]): any;
declare function join(...args: any[]): any;
declare function activate(...args: any[]): any;
declare function shift(...args: any[]): any;
declare function throw_item(...args: any[]): any;
declare function can_use(...args: any[]): any;
declare function use(...args: any[]): any;
declare function use_skill(name: string, target?: any, extra_arg?: any): any;
declare function reduce_cooldown(...args: any[]): any;
declare function bank_deposit(...args: any[]): any;
declare function bank_withdraw(...args: any[]): any;
declare function bank_store(...args: any[]): any;
declare function bank_retrieve(...args: any[]): any;
declare function bank_swap(...args: any[]): any;
declare function swap(...args: any[]): any;
declare function locate_item(...args: any[]): any;
declare function quantity(...args: any[]): any;
declare function item_properties(...args: any[]): any;
declare function item_grade(...args: any[]): any;
declare function item_value(...args: any[]): any;
declare function transport(...args: any[]): any;
declare function leave(...args: any[]): any;
declare function is_paused(...args: any[]): any;
declare function pause(...args: any[]): any;
declare function get_socket(...args: any[]): any;
declare function get_map(...args: any[]): any;
declare function set_message(text: string, color?: string): void;
declare function game_log(message: any, color?: string): void;
declare function log(message: any, color?: string): void;
declare function safe_log(...args: any[]): any;
declare function get_focus(...args: any[]): any;
declare function get_target_of(...args: any[]): any;
declare function get_target(): Entity | null;
declare function get_targeted_monster(): Entity | null;
declare function change_target(target: Entity | string | null): void;
declare function can_move_to(...args: any[]): any;
declare function xmove(x: number, y: number): any;
/** True if target is within attack/skill range. */
declare function is_in_range(target: Entity, skill?: string): boolean;
declare function is_on_cooldown(skill: string): boolean;
/** True if you can attack target now (in range, not disabled, attack ready). */
declare function can_attack(target: Entity): boolean;
declare function can_heal(target: Entity): boolean;
declare function is_moving(...args: any[]): any;
declare function is_transporting(...args: any[]): any;
/** Attack a monster or player. */
declare function attack(target: Entity | string): Promise<any> | any;
declare function heal(target: Entity | string): Promise<any> | any;
declare function buy(...args: any[]): any;
declare function buy_with_gold(...args: any[]): any;
declare function buy_with_shells(...args: any[]): any;
declare function sell(...args: any[]): any;
declare function consume(...args: any[]): any;
declare function equip(...args: any[]): any;
declare function equip_batch(...args: any[]): any;
declare function unequip(...args: any[]): any;
declare function lock_item(...args: any[]): any;
declare function seal_item(...args: any[]): any;
declare function unlock_item(...args: any[]): any;
declare function open_stand(...args: any[]): any;
declare function close_stand(...args: any[]): any;
declare function trade(...args: any[]): any;
declare function trade_buy(...args: any[]): any;
declare function trade_sell(...args: any[]): any;
declare function wishlist(...args: any[]): any;
declare function giveaway(...args: any[]): any;
declare function join_giveaway(...args: any[]): any;
declare function upgrade(...args: any[]): any;
declare function compound(...args: any[]): any;
declare function craft(...args: any[]): any;
declare function auto_craft(...args: any[]): any;
declare function exchange(...args: any[]): any;
declare function exchange_buy(...args: any[]): any;
declare function say(...args: any[]): any;
declare function party_say(...args: any[]): any;
declare function pm(...args: any[]): any;
declare function move(x: number, y: number): any;
declare function cruise(...args: any[]): any;
declare function equip_cx(...args: any[]): any;
declare function show_json(...args: any[]): any;
declare function get_characters(...args: any[]): any;
declare function get_servers(...args: any[]): any;
declare function get_party(...args: any[]): any;
declare function get_player(...args: any[]): any;
declare function get_monster(...args: any[]): any;
declare function get_entity(...args: any[]): any;
declare function find_npc(...args: any[]): any;
/** Nearest monster matching optional filters (e.g. {min_xp, max_att}). */
declare function get_nearest_monster(args?: any): Entity | null;
declare function get_nearest_hostile(args?: any): Entity | null;
declare function get_nearest_npc(...args: any[]): any;
declare function use_hp_or_mp(...args: any[]): any;
declare function loot(...args: any[]): any;
declare function get_chests(...args: any[]): any;
declare function send_gold(...args: any[]): any;
declare function send_item(...args: any[]): any;
declare function send_cx(...args: any[]): any;
declare function send_mail(...args: any[]): any;
declare function destroy(...args: any[]): any;
declare function send_party_invite(...args: any[]): any;
declare function send_party_request(...args: any[]): any;
declare function accept_party_invite(...args: any[]): any;
declare function accept_party_request(...args: any[]): any;
declare function leave_party(...args: any[]): any;
declare function kick_party_member(...args: any[]): any;
declare function accept_magiport(...args: any[]): any;
declare function unfriend(...args: any[]): any;
declare function respawn(...args: any[]): any;
declare function set_home(...args: any[]): any;
declare function handle_death(...args: any[]): any;
declare function handle_command(...args: any[]): any;
declare function send_cm(...args: any[]): any;
declare function on_disappear(...args: any[]): any;
declare function on_combined_damage(...args: any[]): any;
declare function on_party_invite(...args: any[]): any;
declare function on_party_request(...args: any[]): any;
declare function on_destroy(...args: any[]): any;
declare function on_draw(...args: any[]): any;
declare function on_game_event(...args: any[]): any;
declare function draw_line(...args: any[]): any;
declare function draw_circle(...args: any[]): any;
declare function clear_drawings(...args: any[]): any;
declare function auto_reload(...args: any[]): any;
declare function get(...args: any[]): any;
declare function set(...args: any[]): any;
declare function game(...args: any[]): any;
declare function preview_item(...args: any[]): any;
declare function set_skillbar(...args: any[]): any;
declare function set_keymap(...args: any[]): any;
declare function map_key(key: string, skill: string, code?: string): void;
declare function unmap_key(key: string): void;
declare function reset_mappings(...args: any[]): any;
declare function load_code(name: string | number, onerror?: any): void;
declare function require_code(name: string | number): any;
declare function upload_code(...args: any[]): any;
declare function get_active_code_slot(...args: any[]): any;
declare function get_edited_code_slot(...args: any[]): any;
declare function disconnect(...args: any[]): any;
declare function smart_move(dest: any, on_done?: Function): any;
declare function stop(...args: any[]): any;
declare function performance_trick(...args: any[]): any;
declare function distance(...args: any[]): any;
declare function can_walk(...args: any[]): any;
declare function can_transport(...args: any[]): any;
declare function is_disabled(...args: any[]): any;
declare function is_number(...args: any[]): any;
declare function is_string(...args: any[]): any;
declare function is_function(...args: any[]): any;
declare function is_object(...args: any[]): any;
declare function is_array(...args: any[]): any;
